In [1]:
import numpy as np


In [2]:
lst = [1,2,3,4]
np.array(lst)

array([1, 2, 3, 4])

In [8]:
lst1 = [1,2,3,4]
lst2=[2,3,5,6]
lst3= [5,4,3,1]
arr1 = np.array([lst1,lst2,lst3])
arr1.shape


(3, 4)

In [7]:
arr = [1,2,3,4,5]
# gives only last element
arr[-1]

# get all element except last
arr[:-1]

# reverse
arr[::-1]

[5, 4, 3, 2, 1]

In [ ]:
arr1[:,1]
# in multi dimension->1st column

array([2, 3, 4])

In [11]:
arr1[1:,1:3]

array([[3, 5],
       [4, 3]])

In [14]:
arr1[1:,2:]

array([[5, 6],
       [3, 1]])

In [15]:
arr1[:,2:]

array([[3, 4],
       [5, 6],
       [3, 1]])

In [16]:
arr1[0:,2:]

array([[3, 4],
       [5, 6],
       [3, 1]])

In [17]:
arr1[:,0::2]

array([[1, 3],
       [2, 5],
       [5, 3]])

In [19]:
a= np.array([1,2,3,5])
a<2

array([ True, False, False, False])

In [ ]:
# mechanismm to create array
# till 20 with gap 2 starting 1
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
# till 30 gap3
np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])